Feature/wfe from model20211031 again
JASMINE-Mission/jasmine-imagesim pull request #72
Opened 2021-11-24 04:57 UTC by tkamizuka

Fringe37 形式の Zernike ファイルから各所の WFE を計算して
mkimage.py の計算にも反映させる PR (以前のは未完でした)。
こちらも完了し次第 review request を出しますので、
その際によろしくお願いします (そこまではこのまま置いておいてください)。

2021-11-29 09:39 UTC, tkamizuka commented
とりあえず wfe の生成まではうまく動いてそうですので、review を @HajimeKawahara さんと @kataza さんにお願いしたいと思います。何卒よろしくお願いいたします。

2021-11-29 09:41 UTC, tkamizuka commented
ctl.json まわりもあるので @xr0038 さんにも review をお願いしたいと思います。何卒よろしくお願いいたします。

2021-11-29 13:43 UTC, HajimeKawahara commented on params/templates/ctl.json
> +    "val": "/home/kamizuka/WFEfromModel/FringeZernike_2D-s1.csv"},
Should be a common directory?

2021-11-29 13:45 UTC, xr0038 requested changes
設定ファイル周りを確認しました．`FringeZernike_2D-s1.csv` へのパスは編集が前提だと思うので `README.md` に対応する記述を加えておいたほうがよいかと思います．

2021-11-29 13:45 UTC, xr0038 commented on params/templates/ctl.json
> +    "val": "/home/kamizuka/WFEfromModel/FringeZernike_2D-s1.csv"},
`README.md` に `ctl.json` を編集するように追記しておくのがよいでしょうか．

2021-11-29 13:53 UTC, HajimeKawahara commented on params/templates/ctl.json
> +    "val": "/home/kamizuka/WFEfromModel/FringeZernike_2D-s1.csv"},
Templateにある`FringeZernike_2D-s1.csv`ではだめなんでしたっけ?
一応今の最新develop版ではparamsディレクトリにケースごとのディレクトリを作成しています。

2021-11-29 14:23 UTC, xr0038 commented on params/templates/ctl.json
> +    "val": "/home/kamizuka/WFEfromModel/FringeZernike_2D-s1.csv"},
> TemplateにあるFringeZernike_2D-s1.csvではだめなんでしたっけ?

おそらくそのファイルを使うことを想定しているのだと思います．いずれにしろローカル環境のパスが書かれることになりそうなので `README.md` の該当箇所 (Examples?) に適切なパスに編集するよう追記するのがいいかなと．

>  一応今の最新develop版ではparamsディレクトリにケースごとのディレクトリを作成しています。

ケースごとに開発しやすくなりますが，それはそれで管理が大変になりそうな予感も……．

2021-11-29 14:38 UTC, tkamizuka commented on params/templates/ctl.json
> +    "val": "/home/kamizuka/WFEfromModel/FringeZernike_2D-s1.csv"},
おっとすみません。ご指摘の通り templates の中の csv ファイルで問題ありません。が、大澤さんのご指摘もごもっともです。det.json には intrapix の csv ファイルの記述があり、src/jis/pixsim/data のなかの csv を指定していました。あれはどのようにして path が通っているのでしょうか。同じような形で src/jis/photonsim/data みたいなところを作って、そこに csv を置いて参照することでローカル環境のパスの記述を避ける方法もある気がしました。ご意見いただけますと幸いです。

2021-11-29 14:55 UTC, xr0038 commented on params/templates/ctl.json
> +    "val": "/home/kamizuka/WFEfromModel/FringeZernike_2D-s1.csv"},
> det.json には intrapix の csv ファイルの記述があり、src/jis/pixsim/data のなかの csv を指定していました。

intrapix のファイルは `MANIFEST.in` にファイルを記述することでパッケージの内部ファイルとしてインストールさせています．`readflat.read_intrapix()` ではファイルを読み出すときに内部ファイルを先に検索して，見つからなかったら単純に相対パスとして読みに行くという手順を仕込んでいます．ここでも同じ方法を実装することは可能です．

……自分で仕込んでおいてアレなのですが，カレントディレクトリに同じディレクトリ構成でファイルが置いてあると大変混乱するので，ちょっと強くプッシュしづらいな……ということもあって冒頭のコメントでは言及しませんでした．

とりあえず今回は intrapix 方式 (ローカル環境のパスを記述しない方針を優先) を採用して，混乱を生まないような設定ファイルの実装を別の issue として考えるとかはどうでしょうか．あるいは今回は `README.md` に一言追記するだけにして "ローカル環境のパス" 問題は後でまとめて対処するのでも問題ないと思います．

2021-11-30 01:40 UTC, tkamizuka commented
MANIFEST.in に当該 csv を include するよう記載して (include src/jis/photonsim/data/FringeZernike_2D-s1.csv)、
wfe.py にて下記のように記述してみたのですがどうも動きません。
````
    try:
        fname = pkgutil.get_data('photonsim', filename)
        print(fname)
    except Exception as e:
        fname = filename
    za_functions = read_FringeZernike37(fname, scale)
````
print(fname) で None と表示されるのです…。
何か根本的に pkgutil.get_data の使い方を間違えているのでしょうか。
コメントいただけますと幸いです。

2021-11-30 01:42 UTC, tkamizuka commented
あ、get_data の第一引数は jis のままでいいんですね。失礼しました。

2021-11-30 02:04 UTC, tkamizuka commented
get_data でファイルを read してしまいたくなかったので、
get_data は使わずに下記のように処理することを考えました。
````
    dname = os.path.dirname(jis.__file__)
    fname = os.path.join(dname, filename)
    if glob.glob(fname):
        za_functions = read_FringeZernike37(fname, scale)
    else:
        za_functions = read_FringeZernike37(filename, scale)
````
これで jis 以下を探索して、なければローカル以下で探索しますが、
jis 以下とローカル以下はどちらを優先するのがよいでしょうか。
大澤さんの懸念の問題もありますが、先にローカルを探したいと思うのが
人情だったりしますでしょうか…。ご意見お伺いしたいです。
@xr0038 @HajimeKawahara

2021-11-30 02:32 UTC, xr0038 commented
> これで jis 以下を探索して、なければローカル以下で探索しますが、 jis 以下とローカル以下はどちらを優先するのがよいでしょうか。 大澤さんの懸念の問題もありますが、先にローカルを探したいと思うのが 人情だったりしますでしょうか…。

まずは `intrapix` と同様の挙動を実装するという点でこちらの内容で問題ないように思います．

`MANIFEST.in` で取り込むデータは使い方的にはデフォルト値に相当するものだと思います．もし `jis` 以下に格納するファイルが複数種類にならないのであれば，「設定ファイルで空文字列が指定された場合にはデフォルト値として `jis` から決められたファイルを探しに行く」という挙動もありかなと思いました．ユーザの入力は必ず反映されるので僕が懸念した混乱は起きないはずです．

2021-11-30 02:36 UTC, tkamizuka commented
了解しました。jis 以下の格納ファイルが今後数種類になることはありうると思うので、とりあえず現行の実装で行こうと思います。

2021-11-30 02:43 UTC, tkamizuka commented
ということで、 @xr0038 さんからのご要望にはこれで答えられましたでしょうか。ご確認ください。

2021-11-30 02:51 UTC, xr0038 approved these changes
:+1:

2021-11-30 04:48 UTC, tkamizuka commented
こちら @HajimeKawahara さんも OK でしょうか。

@kataza さんには zernike.py, wfe.py, psf.py だけでもご確認いただければと思います…。

2021-11-30 04:49 UTC, HajimeKawahara approved these changes

2021-12-16 07:09 UTC, merged