Feature/drift params20220731
JASMINE-Mission/jasmine-imagesim pull request #97
Opened 2022-07-31 06:58 UTC by tkamizuka

drift.json のフォーマットを他の json とあわせ、説明書きを追記。
この変更にあわせて extract_json も修正。
ご確認のほど、よろしくおねがいいたします。

2022-07-31 23:03 UTC, xr0038 requested changes
`drift.json` の定義の変更について了解しました．

- `params` の他のディレクトリに `drift.json` の兄弟がいるのでそちらの変更もお願いします．
- `Drift` のコメントのアップデートも一緒に含めていただけるとありがたいです．

2022-07-31 23:05 UTC, xr0038 commented
……ところで `init=False` のせいで現在まともに動いていない状態でしょうか？自分の環境でも `extract_json` 関数が以下のエラーを吐くことを確認しました．

```
AttributeError: 'Drift' object has no attribute 'drift_time'
```

2022-07-31 23:26 UTC, tkamizuka commented
> - `params` の他のディレクトリに `drift.json` の兄弟がいるのでそちらの変更もお願いします．

この兄弟って何者なのでしょうか。今後も継続サポートを必要としますでしょうか。必要であればアップデートします。必要ないのであればメンテ負担軽減で削除しようとも思いますが、ご確認いただけますでしょうか。

> - `Drift` のコメントのアップデートも一緒に含めていただけるとありがたいです．

これ何でしたっけ。何か漏れていたということでしょうか。読解力が不足していてすみません…。

2022-07-31 23:36 UTC, tkamizuka commented
> ……ところで `init=False` のせいで現在まともに動いていない状態でしょうか？自分の環境でも `extract_json` 関数が以下のエラーを吐くことを確認しました．

こちらですが、関数単体を実行するとエラーを出しますが、`a=Drift(hogehoge)` みたいにして使うとエラーを出しません。とりあえずそれで動くので仕様と思ってスルーしましたが…。

2022-07-31 23:48 UTC, tkamizuka commented
> > ……ところで `init=False` のせいで現在まともに動いていない状態でしょうか？自分の環境でも `extract_json` 関数が以下のエラーを吐くことを確認しました．
> 
> こちらですが、関数単体を実行するとエラーを出しますが、`a=Drift(hogehoge)` みたいにして使うとエラーを出しません。とりあえずそれで動くので仕様と思ってスルーしましたが…。

いろいろみていると皆さん `default` オプション使うか `__post_init__` 使うかして何かしらの値が入るようにして使っているような感を持ちましたが、そんなルールを明記したものには当たれていません…。

2022-07-31 23:49 UTC, xr0038 commented
兄弟は正直いないほうが良いと思っています……動かない version が同居しているのもよくないですし特に使われていないようであれば削除したいところはあります．

> `Drift` のコメントのアップデート

`Drift` クラスの定義直後に書いてあるコメントで `Drift velocity in ???.` とかいうところです！

2022-07-31 23:52 UTC, xr0038 commented
なんとなくですが `a = Drift(arguments)` はオッケーで `Drift(arguments)` はエラーを吐くという挙動はちょっとイヤらしい (放置しておきたくない) 気はするのですよね……．

2022-08-01 00:20 UTC, tkamizuka commented
> 兄弟は正直いないほうが良いと思っています……動かない version が同居しているのもよくないですし特に使われていないようであれば削除したいところはあります．

名前的に兄弟を作ったのは @HajimeKawahara さんな気がするので河原さんにご確認いただきましょう。

> > `Drift` のコメントのアップデート
> 
> 
> 
> `Drift` クラスの定義直後に書いてあるコメントで `Drift velocity in ???.` とかいうところです！

了解しました。

2022-08-01 00:20 UTC, tkamizuka commented
> なんとなくですが `a = Drift(arguments)` はオッケーで `Drift(arguments)` はエラーを吐くという挙動はちょっとイヤらしい (放置しておきたくない) 気はするのですよね……．

DefaultでNone入れときますか？

2022-08-01 00:58 UTC, xr0038 commented
下手な数値を入れるよりは `None` を入れておいたほうが良さそうですね．賛成します．

2022-08-01 02:36 UTC, tkamizuka commented
@xr0038 
Drift のコメントの件と default 値の方修正しましたのでご確認ください。

@HajimeKawahara 
params dir. にある exoflat, planet というのは今後もサポートすべきものなのかご確認ください。

2022-08-01 09:05 UTC, tkamizuka commented
動作試験さぼってすみません。
そのままでは動かなかったのですが、動くように改良しました。
引き続きよろしくお願いいたします @xr0038 @HajimeKawahara

2022-08-03 07:43 UTC, xr0038 approved these changes
更新内容を確認しました．ありがとうございます．
兄弟を処するかについては @HajimeKawahara さん確認よろしくお願いします．

2022-08-04 10:17 UTC, xr0038 commented
> 惑星用は何らかの形式ではサポートが必要ですね、、、

かわはらさんのコメント on Slack

2022-08-04 10:20 UTC, xr0038 commented
サポートのやり方として `params/template` のコピーを作るのはあまり筋が良くないと思っています．とはいえちゃんと「サポート」するには仕組みを整える必要があるので，とりあえず今回は書き換えた `drift.json` を兄弟に分け与えて，処する方法を考える (issue 行き？) という方針でどうでしょうか？ @tkamizuka

2022-08-04 10:31 UTC, tkamizuka commented
了解しました。対応しまし…codeclimate が引っかかりました。

2022-08-04 10:34 UTC, tkamizuka commented
が、jis への codeclimate は追々だったと思うので、review のほど何卒よろしくお願いいたします。 @HajimeKawahara

2022-08-04 11:49 UTC, xr0038 commented
すみません……とりあえず設定してみただけなので Code Climate の check は無視してください……

2022-08-17 06:52 UTC, tkamizuka commented
@HajimeKawahara さま。お忙しいところ恐縮ですが、review のほうよろしくお願いいたします。

2022-08-17 07:00 UTC, HajimeKawahara approved these changes

2022-08-17 07:01 UTC, merged